apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: doughnut-httproute
  namespace: red-hat-provisions
spec:
  parentRefs:
    - name: doughnut-gateway
      sectionName: http
  rules:
    - backendRefs:
        - name: doughnut-frontend
          port: 8080
